"""initial schema

Revision ID: 168d079a7f17
Revises: 
Create Date: 2026-08-15 19:06:08.183795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '168d079a7f17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('native_name', sa.String(length=64), nullable=False),
    sa.Column('supports_learning_engine', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_table('skills',
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('cefr_level', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=False
    )
    op.create_index(op.f('ix_skills_code'), 'skills', ['code'], unique=False)
    op.create_index(op.f('ix_skills_language_code'), 'skills', ['language_code'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assessment_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_ability_estimate', sa.Float(), nullable=False),
    sa.Column('current_difficulty', sa.String(length=4), nullable=False),
    sa.Column('result_cefr_level', sa.String(length=4), nullable=True),
    sa.Column('result_confidence_interval', sa.Float(), nullable=True),
    sa.Column('result_breakdown', sa.JSON(), nullable=False),
    sa.Column('result_strengths', sa.JSON(), nullable=False),
    sa.Column('result_weaknesses', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_sessions_user_id'), 'assessment_sessions', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learner_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('native_language_code', sa.String(length=8), nullable=False),
    sa.Column('target_language_code', sa.String(length=8), nullable=False),
    sa.Column('cefr_level', sa.String(length=4), nullable=False),
    sa.Column('proficiency_confidence', sa.Float(), nullable=False),
    sa.Column('grammar_ability', sa.Float(), nullable=False),
    sa.Column('vocabulary_ability', sa.Float(), nullable=False),
    sa.Column('speaking_ability', sa.Float(), nullable=False),
    sa.Column('listening_ability', sa.Float(), nullable=False),
    sa.Column('reading_ability', sa.Float(), nullable=False),
    sa.Column('writing_ability', sa.Float(), nullable=False),
    sa.Column('pronunciation_ability', sa.Float(), nullable=False),
    sa.Column('fluency_ability', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('learning_speed', sa.Float(), nullable=False),
    sa.Column('current_difficulty', sa.String(length=16), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('total_study_minutes', sa.Integer(), nullable=False),
    sa.Column('last_active_at', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('learning_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=True),
    sa.Column('objective', sa.String(length=128), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('ai_personality', sa.String(length=32), nullable=False),
    sa.Column('correction_style', sa.String(length=32), nullable=False),
    sa.Column('voice_speed', sa.Float(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('store_raw_audio', sa.Boolean(), nullable=False),
    sa.Column('personalization_enabled', sa.Boolean(), nullable=False),
    sa.Column('analytics_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ai_tokens_used_month', sa.Integer(), nullable=False),
    sa.Column('voice_minutes_used_month', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('agent_decisions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reason_summary', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.String(length=128), nullable=True),
    sa.Column('target_skill_id', sa.UUID(), nullable=True),
    sa.Column('inputs_snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ),
    sa.ForeignKeyConstraint(['target_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_decisions_user_id'), 'agent_decisions', ['user_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('assessment_session_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('skill_area', sa.String(length=24), nullable=False),
    sa.Column('difficulty', sa.String(length=4), nullable=False),
    sa.Column('prompt', sa.String(length=1000), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_session_id'], ['assessment_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_questions_assessment_session_id'), 'assessment_questions', ['assessment_session_id'], unique=False)
    op.create_table('learner_errors',
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('error_type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('weakness_score', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trend', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_errors_category'), 'learner_errors', ['category'], unique=False)
    op.create_index(op.f('ix_learner_errors_last_seen_at'), 'learner_errors', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_learner_errors_learner_profile_id'), 'learner_errors', ['learner_profile_id'], unique=False)
    op.create_table('learner_memories',
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('related_skill_id', sa.UUID(), nullable=True),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('last_reinforced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['source_session_id'], ['learning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_memories_learner_profile_id'), 'learner_memories', ['learner_profile_id'], unique=False)
    op.create_table('learning_goals',
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_preferences',
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('conversation_affinity', sa.Float(), nullable=False),
    sa.Column('quiz_affinity', sa.Float(), nullable=False),
    sa.Column('reading_affinity', sa.Float(), nullable=False),
    sa.Column('listening_affinity', sa.Float(), nullable=False),
    sa.Column('preferred_explanation_length', sa.String(length=16), nullable=False),
    sa.Column('example_preference', sa.Float(), nullable=False),
    sa.Column('repetition_preference', sa.Float(), nullable=False),
    sa.Column('challenge_tolerance', sa.Float(), nullable=False),
    sa.Column('correction_style', sa.String(length=16), nullable=False),
    sa.Column('preferred_pace', sa.String(length=16), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('preferred_topics', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_profile_id')
    )
    op.create_table('learning_recommendations',
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reason_summary', sa.String(length=500), nullable=False),
    sa.Column('target_skill_id', sa.UUID(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_recommendations_learner_profile_id'), 'learning_recommendations', ['learner_profile_id'], unique=False)
    op.create_table('messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=False),
    sa.Column('input_mode', sa.String(length=16), nullable=False),
    sa.Column('correction_needed', sa.Boolean(), nullable=True),
    sa.Column('correction_priority', sa.String(length=16), nullable=True),
    sa.Column('teaching_intent', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('skill_mastery',
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct_attempts', sa.Integer(), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_estimate', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_mastery_learner_profile_id'), 'skill_mastery', ['learner_profile_id'], unique=False)
    op.create_index(op.f('ix_skill_mastery_next_review_at'), 'skill_mastery', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_skill_mastery_skill_id'), 'skill_mastery', ['skill_id'], unique=False)
    op.create_table('teaching_strategies',
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_strategies_learner_profile_id'), 'teaching_strategies', ['learner_profile_id'], unique=False)
    op.create_table('vocabulary_items',
    sa.Column('learner_profile_id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('translation', sa.String(length=256), nullable=False),
    sa.Column('part_of_speech', sa.String(length=32), nullable=True),
    sa.Column('example_sentence', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('pronunciation_ipa', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('times_confused_with', sa.JSON(), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_profile_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_items_learner_profile_id'), 'vocabulary_items', ['learner_profile_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_items_next_review_at'), 'vocabulary_items', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_vocabulary_items_word'), 'vocabulary_items', ['word'], unique=False)
    op.create_table('voice_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stt_provider', sa.String(length=32), nullable=False),
    sa.Column('tts_provider', sa.String(length=32), nullable=False),
    sa.Column('raw_audio_retained', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_sessions_session_id'), 'voice_sessions', ['session_id'], unique=False)
    op.create_table('assessment_answers',
    sa.Column('assessment_question_id', sa.UUID(), nullable=False),
    sa.Column('user_answer', sa.String(length=1000), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('ability_estimate_after', sa.Float(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_question_id'], ['assessment_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_answers_assessment_question_id'), 'assessment_answers', ['assessment_question_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_message_id', sa.UUID(), nullable=False),
    sa.Column('assistant_message_id', sa.UUID(), nullable=False),
    sa.Column('detected_errors', sa.JSON(), nullable=False),
    sa.Column('difficulty_decision', sa.JSON(), nullable=False),
    sa.Column('teaching_strategy', sa.JSON(), nullable=False),
    sa.Column('agents_invoked', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_session_id'), 'conversation_turns', ['session_id'], unique=False)
    op.create_table('error_occurrences',
    sa.Column('learner_error_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('incorrect_text', sa.String(length=500), nullable=False),
    sa.Column('correct_text', sa.String(length=500), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_error_id'], ['learner_errors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_occurrences_learner_error_id'), 'error_occurrences', ['learner_error_id'], unique=False)
    op.create_table('practice_questions',
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('source_error_id', sa.UUID(), nullable=True),
    sa.Column('source_skill_id', sa.UUID(), nullable=True),
    sa.Column('for_learner_profile_id', sa.UUID(), nullable=True),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=4), nullable=False),
    sa.Column('prompt', sa.String(length=1000), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(length=1000), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['for_learner_profile_id'], ['learner_profiles.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['source_error_id'], ['learner_errors.id'], ),
    sa.ForeignKeyConstraint(['source_skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_questions_fingerprint'), 'practice_questions', ['fingerprint'], unique=False)
    # NOTE: 'semantic_memories' (pgvector) is created in the follow-up migration
    # 0002_semantic_memory, which is isolated specifically because it requires the
    # postgres 'vector' extension — see that migration's docstring.
    op.create_table('speech_analysis',
    sa.Column('voice_session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('transcript', sa.String(length=2000), nullable=False),
    sa.Column('asr_confidence', sa.Float(), nullable=False),
    sa.Column('speaking_score', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('speaking_rate_wpm', sa.Float(), nullable=True),
    sa.Column('pause_count', sa.Integer(), nullable=False),
    sa.Column('filler_word_count', sa.Integer(), nullable=False),
    sa.Column('repeated_word_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speech_analysis_voice_session_id'), 'speech_analysis', ['voice_session_id'], unique=False)
    op.create_table('vocabulary_reviews',
    sa.Column('vocabulary_item_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recalled_correctly', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_item_id'], ['vocabulary_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_reviews_vocabulary_item_id'), 'vocabulary_reviews', ['vocabulary_item_id'], unique=False)
    op.create_table('practice_attempts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('user_answer', sa.String(length=1000), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['practice_questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_attempts_user_id'), 'practice_attempts', ['user_id'], unique=False)
    op.create_table('pronunciation_scores',
    sa.Column('speech_analysis_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('phoneme_scores', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['speech_analysis_id'], ['speech_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pronunciation_scores_speech_analysis_id'), 'pronunciation_scores', ['speech_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pronunciation_scores_speech_analysis_id'), table_name='pronunciation_scores')
    op.drop_table('pronunciation_scores')
    op.drop_index(op.f('ix_practice_attempts_user_id'), table_name='practice_attempts')
    op.drop_table('practice_attempts')
    op.drop_index(op.f('ix_vocabulary_reviews_vocabulary_item_id'), table_name='vocabulary_reviews')
    op.drop_table('vocabulary_reviews')
    op.drop_index(op.f('ix_speech_analysis_voice_session_id'), table_name='speech_analysis')
    op.drop_table('speech_analysis')
    op.drop_index(op.f('ix_practice_questions_fingerprint'), table_name='practice_questions')
    op.drop_table('practice_questions')
    op.drop_index(op.f('ix_error_occurrences_learner_error_id'), table_name='error_occurrences')
    op.drop_table('error_occurrences')
    op.drop_index(op.f('ix_conversation_turns_session_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_assessment_answers_assessment_question_id'), table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_index(op.f('ix_voice_sessions_session_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    op.drop_index(op.f('ix_vocabulary_items_word'), table_name='vocabulary_items')
    op.drop_index(op.f('ix_vocabulary_items_next_review_at'), table_name='vocabulary_items')
    op.drop_index(op.f('ix_vocabulary_items_learner_profile_id'), table_name='vocabulary_items')
    op.drop_table('vocabulary_items')
    op.drop_index(op.f('ix_teaching_strategies_learner_profile_id'), table_name='teaching_strategies')
    op.drop_table('teaching_strategies')
    op.drop_index(op.f('ix_skill_mastery_skill_id'), table_name='skill_mastery')
    op.drop_index(op.f('ix_skill_mastery_next_review_at'), table_name='skill_mastery')
    op.drop_index(op.f('ix_skill_mastery_learner_profile_id'), table_name='skill_mastery')
    op.drop_table('skill_mastery')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_learning_recommendations_learner_profile_id'), table_name='learning_recommendations')
    op.drop_table('learning_recommendations')
    op.drop_table('learning_preferences')
    op.drop_table('learning_goals')
    op.drop_index(op.f('ix_learner_memories_learner_profile_id'), table_name='learner_memories')
    op.drop_table('learner_memories')
    op.drop_index(op.f('ix_learner_errors_learner_profile_id'), table_name='learner_errors')
    op.drop_index(op.f('ix_learner_errors_last_seen_at'), table_name='learner_errors')
    op.drop_index(op.f('ix_learner_errors_category'), table_name='learner_errors')
    op.drop_table('learner_errors')
    op.drop_index(op.f('ix_assessment_questions_assessment_session_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_agent_decisions_user_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_table('subscriptions')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_table('learner_profiles')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assessment_sessions_user_id'), table_name='assessment_sessions')
    op.drop_table('assessment_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_language_code'), table_name='skills')
    op.drop_index(op.f('ix_skills_code'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
